;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env14,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env15,@env0
	.byte $00
	.byte $70 ;instrument $04
	.word @env5,@env16,@env0
	.byte $00
	.byte $70 ;instrument $05
	.word @env5,@env17,@env0
	.byte $00
	.byte $70 ;instrument $06
	.word @env6,@env0,@env20
	.byte $00
	.byte $70 ;instrument $07
	.word @env10,@env16,@env21
	.byte $00
	.byte $70 ;instrument $08
	.word @env10,@env17,@env21
	.byte $00
	.byte $30 ;instrument $09
	.word @env1,@env18,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env7,@env0,@env0
	.byte $00
	.byte $70 ;instrument $0b
	.word @env8,@env0,@env20
	.byte $00
	.byte $70 ;instrument $0c
	.word @env9,@env17,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env6,@env0,@env20
	.byte $00
	.byte $30 ;instrument $0e
	.word @env8,@env0,@env20
	.byte $00
	.byte $70 ;instrument $0f
	.word @env5,@env19,@env0
	.byte $00
	.byte $70 ;instrument $10
	.word @env9,@env16,@env0
	.byte $00
	.byte $70 ;instrument $11
	.word @env11,@env16,@env21
	.byte $00
	.byte $b0 ;instrument $12
	.word @env12,@env0,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env13,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $ca,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$07
@env3:
	.byte $cb,$ca,$c9,$c0,$00,$03
@env4:
	.byte $cf,$cb,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env5:
	.byte $c7,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env6:
	.byte $cc,$cb,$ca,$ca,$c9,$03,$c8,$03,$c7,$07,$c6,$08,$c5,$0a,$c4,$0c
	.byte $c3,$0c,$c2,$12,$c1,$19,$c0,$00,$16
@env7:
	.byte $c6,$c2,$c1,$03,$c0,$00,$04
@env8:
	.byte $c4,$02,$c3,$0c,$c2,$0b,$c1,$12,$c0,$00,$08
@env9:
	.byte $c3,$c3,$c2,$03,$c1,$06,$c0,$00,$06
@env10:
	.byte $c3,$c3,$c2,$05,$c1,$05,$c0,$00,$06
@env11:
	.byte $c3,$c3,$c2,$c2,$c1,$04,$c0,$00,$06
@env12:
	.byte $c6,$c6,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$03,$c2,$05,$c1,$05
	.byte $c0,$00,$10
@env13:
	.byte $cf,$c0,$cf,$c0,$00,$03
@env14:
	.byte $cc,$c0,$00,$01
@env15:
	.byte $c8,$c0,$c4,$00,$02
@env16:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$00,$00
@env17:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env18:
	.byte $c0,$05,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$b5,$b4,$b3,$b2
	.byte $b1,$b0,$af,$ae,$ad,$ac,$ab,$aa,$a9,$a8,$a8,$a7,$a7,$a6,$a6,$a5
	.byte $a5,$a4,$a4,$a3,$a3,$a2,$a2,$a1,$a1,$00,$28
@env19:
	.byte $c0,$c0,$c3,$c3,$c8,$c8,$00,$00
@env20:
	.byte $c0,$0f,$c1,$02,$c2,$02,$c1,$02,$c0,$c0,$c0,$00,$02
@env21:
	.byte $c4,$00,$00


@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $bf
@ref1:
	.byte $bf
@ref2:
	.byte $8f,$82,$36,$9d,$36,$8d
@ref3:
	.byte $8f,$36,$a5,$36,$85
@ref4:
	.byte $8f,$38,$9d,$38,$8d
@ref5:
	.byte $8f,$38,$ad
	.byte $ff,$05
	.word @ref4
@ref7:
	.byte $8f,$38,$a5,$38,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $80,$38,$85,$84,$38,$85,$80,$38,$85,$84,$3e,$85,$80,$34,$85,$84
	.byte $34,$85,$80,$34,$85,$84,$3e,$85
@ref9:
	.byte $80,$38,$85,$84,$38,$85,$80,$38,$85,$84,$3e,$95,$80,$34,$85,$84
	.byte $3e,$85
@ref10:
	.byte $38,$85,$80,$38,$85,$38,$85,$3e,$85,$34,$85,$34,$85,$34,$85,$3e
	.byte $85
@ref11:
	.byte $38,$85,$38,$85,$38,$85,$3e,$95,$34,$85,$3e,$85
@ref12:
	.byte $84,$38,$85,$38,$85,$38,$85,$3e,$85,$34,$85,$34,$85,$34,$85,$3e
	.byte $85
	.byte $ff,$0c
	.word @ref11
@ref14:
	.byte $38,$85,$38,$85,$38,$85,$3e,$85,$34,$85,$34,$85,$34,$85,$3e,$85
	.byte $ff,$0c
	.word @ref11
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $bf
@ref17:
	.byte $bf
@ref18:
	.byte $bf
@ref19:
	.byte $bf
@ref20:
	.byte $86,$38,$85,$42,$85,$3e,$85,$4e,$85,$38,$85,$42,$85,$3e,$85,$4e
	.byte $85
@ref21:
	.byte $38,$85,$42,$85,$3e,$85,$4e,$85,$38,$85,$42,$85,$3e,$85,$4e,$85
@ref22:
	.byte $bf
@ref23:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $bf
@ref25:
	.byte $bf
@ref26:
	.byte $bf
@ref27:
	.byte $bf
@ref28:
	.byte $bf
@ref29:
	.byte $bf
@ref30:
	.byte $bf
@ref31:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
